# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/components/designer/DetailsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetailsDialog(object):
    def setupUi(self, DetailsDialog):
        DetailsDialog.setObjectName("DetailsDialog")
        DetailsDialog.resize(421, 367)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DetailsDialog.sizePolicy().hasHeightForWidth())
        DetailsDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(DetailsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(DetailsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DetailsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(DetailsDialog)
        self.buttonBox.accepted.connect(DetailsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DetailsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DetailsDialog)

    def retranslateUi(self, DetailsDialog):
        _translate = QtCore.QCoreApplication.translate
        DetailsDialog.setWindowTitle(_translate("DetailsDialog", "Details"))
